const 
  STATE_READY = 1,
  STATE_PROCESSING = 2,
  STATE_STARTED = 4,
  STATE_ENDED = 8,
  STATE_FAILED = 16,
  STATE_WAITING_FOR_CONDITIONS = 32

export {
  STATE_READY,
  STATE_PROCESSING,
  STATE_STARTED,
  STATE_ENDED,
  STATE_FAILED,
  STATE_WAITING_FOR_CONDITIONS,
}
